name: Deploy to GitHub Pages


on:
  push:
    branches:
      - main
    paths:
      - index.html  # Only changes in index.html will trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2


    # Set up GitHub Pages
    - name: Set up GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./  # Publish to root directory
